---
- name: "Add a new user"
  hosts: all
  tasks:
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      user:
        name: jbrain
        comment: John Brain
        uid: 1040
        group: wheel  